services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: atd
      MYSQL_PASSWORD: atd
      MYSQL_DATABASE: atd
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "--silent"
        ]
      interval: 5s
      timeout: 3s
      retries: 4
      start_period: 20s
    volumes:
      - ./data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: api
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    env_file:
      - .env
    # healthcheck:
    #   test: curl --fail http://localhost:5000/api/user || exit 1
    #   interval: 5s
    #   timeout: 3s
    #   retries: 5
    #   start_period: 20s
    volumes:
      - ./api:/app

  frontend:
    build:
      context: web
      dockerfile: Dockerfile
    # depends_on:
    #   api:
    #     condition: service_healthy
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./web:/app
    environment:
      - WATCHPACK_POLLING=true
