services:
  db:
    image: mysql:8
    environment:
      MYSQL_PASSWORD: ${HOST_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: azerty
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 5s
      timeout: 3s
      retries: 4
      start_period: 20s
    volumes:
      # - ./db-data:/var/lib/mysql
      - ./database/database.sql:/docker-entrypoint-initdb.d/1.sql


  backend:
    build:
      context: api
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "5000:6001"