services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${MYSQL_PORT}:3306
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "--silent"
        ]
      interval: 5s
      timeout: 3s
      retries: 4
      start_period: 20s
    volumes:
      - ./data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - web

  backend:
    image: ashinatd/au-temps-donne:api-flask
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - ${FLASK_PORT}:5000
    networks:
      - web

    

  frontend:
    image: ashinatd/au-temps-donne:web
    ports:
      - ${REACT_PORT}:3000
    restart: always
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - /app/node_modules
    networks:
      - web

networks:
  web:
    driver: bridge